### ISSUE TITLE
Problems with A4 print format

### ISSUE THREAD

**Issue by Thuffir** [bombmanual/german#3]
Trying to print the manual in A4 format (with Chrome) results in some of the pages displaced:

![image](https://cloud.githubusercontent.com/assets/6106671/22975688/e680cb82-f387-11e6-9282-93b48e6074cc.png)

![image](https://cloud.githubusercontent.com/assets/6106671/22975697/ebf3efae-f387-11e6-98b2-75cdb83e9943.png)

![image](https://cloud.githubusercontent.com/assets/6106671/22975714/f28f1bcc-f387-11e6-825e-8980a2508c98.png)

**Comment by 3breadt** [comment]
Should have been fixed by commit c8734f025fc43bf512546ca1b62d2b85693a8d2f. But the github.io site has not yet been updated to the new version it seems.

I uploaded a PDF of the updated version here: https://dl.dropboxusercontent.com/u/2389669/Keep%20Talking%20and%20Nobody%20Explodes%20German.pdf

**Comment by Thuffir** [comment]
Indeed. The actual Master seems to be OK.
